### ISSUE TITLE
Reply already submitted exception in method channel

### ISSUE THREAD

**Issue by Sukendh** [Blasanka/aws_s3_plugin#6]
I'm using another method channel to show a notification in the android side when the upload begin and finish. When I upload 2 files simultaneously I'm getting an exception like this. I couldn't use the result on my method channel.

`java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(13725): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/AndroidRuntime(13725): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
E/AndroidRuntime(13725): 	at com.blasanka.s3flutter.aws_s3.AwsS3Plugin$Transfer.onStateChanged(AwsS3Plugin.java:210)
E/AndroidRuntime(13725): 	at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$2.run(TransferStatusUpdater.java:206)
E/AndroidRuntime(13725): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(13725): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(13725): 	at android.os.Looper.loop(Looper.java:228)
E/AndroidRuntime(13725): 	at android.app.ActivityThread.main(ActivityThread.java:7782)
E/AndroidRuntime(13725): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13725): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(13725): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)`

**Comment by DevuSeeroo** [comment]
have you found any solution

**Comment by Sukendh** [comment]
Not yet. I just removed notification part.

**Comment by DevuSeeroo** [comment]
> Not yet. I just removed notification part.

how??
I am still stuck on that portion
